name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang libgtest-dev cppcheck

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

    - name: Check code style
      run: |
        git clone https://github.com/cpplint/cpplint.git
        cpplint/cpplint.py --recursive src/*.cpp src/*.h tests/*.cpp

    - name: Run cppcheck
      run: |
        cppcheck --enable=warning,style,performance,portability --inconclusive --force --inline-suppr --template=gcc --quiet --std=c++11 --language=c++ src tests
